### ISSUE TITLE
ValueError when valdiate pd.DataFrame

### ISSUE THREAD

**Issue by xbanke** [seandstewart/typical#106]
* typical version: 2.0.20
* Python version: 3.7.4
* Operating System:

### Description
Hey, @seandstewart, Asigning a value to a field annotated by `pd.DataFrame` with a default value or `Optional[pd.DataFrame]`, will raise `TypeError`. It looks like that this is caused by `pd.DataFrame.__eq__` which is elementwise.

```py
import typic, typing


@typic.klass
class Foo:
    df: typing.Optional[pd.DataFrame] = None

df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
foo = Foo()
foo.df = df  # ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by seandstewart** [comment]
Looks like some logic got screwed up in one of the latest releases. This definitely worked before.
