### ISSUE TITLE
Using typical with a class that has a custom from_dict method

### ISSUE THREAD

**Issue by ahobsonsayers** [seandstewart/typical#127]
* typical version: 2.0.29
* Python version: 3.8.3
* Operating System: Linux

### Description

I have a class with a custom `from_dict` class method that does some stuff and then calls transmute. However I note that the deserializer used in `transmute` creates and then uses a `from_dict` class method internally. This means that because I have defined my own method of the same name that in turn calls transmute, I obviously hit the recursion limit.

Simple example:

```python
@typic.al
@dataclass
class Person:
    name: str
    age: int

    @classmethod
    def from_dict(cls, dict):
        return cls.transmute(dict)


person = Person.from_dict({"name": "Jack", "age": 10})
```

Gives (full stacktrace ommited due to obvious size):
```
  ...
  File "<typical generated deserializer__283563495926319966>", line 7, in deserializer__283563495926319966
  File "/home/arranhs/Desktop/typical/typical.py, line 20, in from_dict
    return cls.transmute(dict)
  File "<typical generated deserializer__283563495926319966>", line 3, in deserializer__283563495926319966
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

And the generated deserializer:

```python
def deserializer__283563495926319966(val):
    _, val = __eval(val) if isinstance(val, (str, bytes)) else (False, val)
    vtype = val.__class__
    if vtype is Person_38601264:
        return val
    val = Person_38601264.from_dict(val)
    return val
```

### What I Did

Naturally the simple solution (and I suppose the good enough one) is to rename my from_dict method. Unfortunately for me this is a breaking change and I would prefer to avoid it.

Is there a way to get around this?  The only path i could see thus far would be to fork the repo and make `from_dict`, `_from_dict`. Would this break anything? Could this feasibly and easily be done in this repo for avoid issues for others since this is a pretty common function name. If not, maybe I can help add a documentation warning as this took me quite a while to understand the root cause of.

On a side note, I also have a to_dict method, and I note you also implement this in typical with `from_dict`. So far I have not noticed any issues having this method and overriding yours, but maybe there is something I am missing. Could this cause issues?

**Comment by seandstewart** [comment]
Hey @ahobsonsayers - 

Apologies for the late response, I’ve been thinking over your problem. The best way forward in my mind is to implement your own class decorator or meta class which decorates you class with typical, and *then* applies a `from_dict` method to your class body. I’m afk but when I’m back at my computer tomorrow I’ll show a post with an example.

**Comment by seandstewart** [comment]
@ahobsonsayers -

Here's an example based on the one you provided:

```python

def delayed_from_dict(cls):
    from_dict = cls.from_dict
    del cls.from_dict
    cls = typic.al(cls)
    cls.from_dict = from_dict
    return cls

@delayed_from_dict
@dataclass
class Person:
    name: str
    age: int

    @classmethod
    def from_dict(cls, dict):
        return cls.transmute(dict)


person = Person.from_dict({"name": "Jack", "age": "10"})
print(person)
#> Person(name='Jack', age=10)
```

This will work with the simple case, and also if you have class-specific transformations in your `from_dict` methods.

As for the `to_dict` support, that's used when determining how to dump an object to its primitive form, so you would need to implement similar handling if you're planning to use typical's `primitive()` method within `to_dict`.

**Comment by ahobsonsayers** [comment]
This is great! I appreciate you spending the time to think it through and pushing me in the right direction. I can see how we could do this with a metaclass too. Thanks again!
