### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ahobsonsayers** [seandstewart/typical#131]
Hey @seandstewart, I have been using typical for a while now and I absolutely love it, far better than every other similar tool out there. I would really like to offer some help to advance it's capability and contribute to some of the features I have seen on your roadmap. 

What things do you most need help with, and if you are open to the idea of some help do you have a platform (Discord etc.) we can discuss on?

Many Thanks!

**Comment by seandstewart** [comment]
Hey @ahobsonsayers!

Thanks for reaching out - I'm so glad you enjoy working with typical. Although I've not explicitly listed `Help Wanted`, I'm open to contributions for any open tickets (be it bugs or roadmapped features!).

I don't currently have a chat instance spun up for typical, as I haven't had the need so far. If we feel that's something that would be helpful I'm sure we could spin up a Discord server and link it in the docs.

To get started, why don't we discuss which issue you'd like to tackle first? Perhaps in the process I can also iron out the long-needed `Contributing` docs!

**Comment by ahobsonsayers** [comment]
Sorry for my tardy reply, work has kept be busy. 

As for the issues id like to tackle i see two that would be most use to be personally

- Support for unions. I have no idea about the possibility of this feature, however looking at pydantic they at least have some support for them, maybe we could draw on inspiration from them?

- Improving custom coercing/validation functions. It would be great if they could be scoped to individual classes rather than have to be registered globally, as well as improving the API and capability. Again, im thinking like how pydantic [__get_validators__](https://pydantic-docs.helpmanual.io/usage/types/#classes-with-__get_validators__). Personally I don't like how that is implemented in pydantic, but its gests across what i am maybe thinking. I sure you have many ideas of your own about this, i saw good discussion in #56

**Comment by seandstewart** [comment]
@ahobsonsayers -

I can't believe a year has passed since this issue was originally posted. Since then, generic Union and tagged Union support is now out in the wild.

I haven't ever had a chance to dig in on your second idea around improved support for custom deserializers/validators, but if you're still interested in digging in, I'm happy to have a chat!
