### ISSUE TITLE
TypedDict JSON schema generation: Optionals and required fields

### ISSUE THREAD

**Issue by syastrov** [seandstewart/typical#14]
So I played around a bit with the new support for TypedDict schema generation and noticed a few things:

```
>>> class G(TypedDict, total=False):
...   a: str
... 
>>> typic.schema(G)
ObjectSchemaField(title='G', properties={'a': StrSchemaField()}, additionalProperties=False, required=('a',))
```

Since the TypedDict is not total, the field `a` is not required to be present, so shouldn't be `required` in the JSON schema.

Also, somewhat related: Making a field `Optional` seems to make it not required even though it doesn't have a default value. But `Optional` just means that the value can be `None`, not that it could be missing.

```
>>> class G(TypedDict, total=True):
...   a: Optional[int]
... 
>>> typic.schema(G)
ObjectSchemaField(title='G', properties={'a': IntSchemaField()}, additionalProperties=False)
```

**Comment by seandstewart** [comment]
I'll take a look at this today - missed this in the TypedDict spec.

**Comment by syastrov** [comment]
Awesome, thanks :)
