### ISSUE TITLE
Coercion from None to str

### ISSUE THREAD

**Issue by syastrov** [seandstewart/typical#15]
I didn't expect that `None` would be coerced to a string for a field marked as `str`. Can that behavior be disabled?

```
>>> @typic.al
... @dataclass
... class Y:
...   a: str
... 
>>> Y(None)
Y(a='None')
```

The same behavior happens if you try to coerce other types:
```
>>> Y(dict)
Y(a="<class 'dict'>")
```

**Comment by seandstewart** [comment]
@syastrov  - You can flag a field as `Optional`, or provide `None` as a default value to prevent automatic coercion to `str`, e.g.,
```python
>>> @typic.al
... @dataclass
... class Y:
...     a: Optional[str]
... 
>>> Y(None)
Y(a=None)

```

Unfortunately, the coercer isn't sophisticated enough to prevent the case of casting certain types and not others, since it's relying on the Python interpreter to raise the `Value-` or `Type-` error.

**Comment by syastrov** [comment]
Here's my use case:

Essentially, I would like to take some JSON (e.g. already parsed into a dict) and validate and construct a dataclass from it (or just use it as a TypedDict after I know the types are validated). While doing that, I'd like to ensure that the types in the dict match the annotated types on the dataclass or TypedDict, and if they don't match, then I'd like to coerce them, but ONLY if the target type is not representable in JSON (e.g. datetime, Decimal, Enums). If the target type is representable in JSON (e.g. it can be returned by `json.loads`: `int`, `str`, etc..), then I don't want to coerce it, but raise validation errors. Basically, I don't want someone writing `null` in their JSON and it being converted to a str `'None'`, but I still want to be able to coerce `str` to `datetime`.

I suppose I could do this validation as a preprocessing step, e.g:
- Generate JSON schema using typical and then validate the input using the JSON schema (it might be slow though).
- Coerce to target type using typical (at this point, presumably it would not be possible to get `ValueError`/`TypeError` because the input is already validated, and typical just does the coercion)

Does that seem like a reasonable approach?

Related to https://github.com/seandstewart/typical/issues/16

Feel free to close this, as now I am just brainstorming out loud :)

**Comment by seandstewart** [comment]
The schema objects returned by typical have a `validate` method that is very fast, thanks to [fastjsonschema](https://horejsek.github.io/python-fastjsonschema/). typical provides the `schema` extra to ensure it's installed. I agree with your approach for validation -> coercion. It will of course be more expensive than just blind coercion, but it will still be decently fast.

**Comment by syastrov** [comment]
Thanks for the response. Good to know that's a sort of recommended approach
