### ISSUE TITLE
How to validate type must be one of list of values?

### ISSUE THREAD

**Issue by ducminhgd** [seandstewart/typical#152]
* typical version: 2.1.3
* Python version: 3.8.5
* Operating System: Ubuntu 20.0

### Description

I would like to validate a string MUST be one of `YES` or `NO`.

### What I Did

```python
@typic.constrained(values=['YES', 'NO'])
class MediaBool(str):
    ...

@typic.klass
class Sample:
    b: MediaBool

sample = Sample(b='yes')
print(sample)
```

**Comment by ducminhgd** [comment]
I found a solution:

```python
@typic.constrained(regex=re.compile('^(YES|NO)$'))
class MediaBool(str):
    ...
```

**Comment by seandstewart** [comment]
> I found a solution:
> 
> ```python
> @typic.constrained(regex=re.compile('^(YES|NO)$'))
> class MediaBool(str):
>     ...
> ```
> 
> or
> 
> ```python
> @typic.klass
> class Media:
>     forced: Optional[Literal['YES', 'NO']] = typic.field('NO', name='FORCED')
> ```

Yes - I would recommend the `Literal` in this case.
