### ISSUE TITLE
callable instance should be the treated as a function or class?

### ISSUE THREAD

**Issue by xbanke** [seandstewart/typical#173]
* typical version: 2.6.4
* Python version: 3.8.5
* Operating System: Centos8

### Description

Hey, @seandstewart . 
By checking `typic.protocals`, I found that it check type of the obj by `inspect.ismethod`, `inspect.isfunction` and `inspect.isclass`. Personally, I think callable instace of a class with `__call__` should be treated as a function, and the protocals should be redirected to the `__call__`.

A function decorated by a class decorator will be treated as class and the `typic.al` could not validate the arguments.

```py
from functools import wraps
import typic


class Wrapped:
    def __init__(self, func):
        self.func = func
    
    def __call__(self, *args, **kwargs):
        return self.func(*args, **kwargs)


def wrapped(func):
    return wraps(func)(Wrapped(func))


@typic.al
@wrapped
def foo(a: int):
    return a


foo('42')  # '42'
foo('abc')  # 'abc'
```

**Comment by seandstewart** [comment]
@xbanke -

I will look into this for a patch release next. If you have a preferred implementation, please feel free to submit a PR 👍
