### ISSUE TITLE
Coercion to Union does not result in error but returns passed in value -- Union could be expanded

### ISSUE THREAD

**Issue by syastrov** [seandstewart/typical#19]
It's stated in the README:

> The following annotations are special forms which cannot be resolved:
> Union
> Any
> Because these signal an unclear resolution, Typical will ignore this flavor of annotation ...

However, when I try to coerce some values to Unions, I didn't expect Typical to *silently* ignore Union annotations: (e.g. it returns a `str` when a `str` is passed in, when none of the Union members are `str`). Since it is ignored, I can't rely on passing my value through coercion to actually get the correct type returned to me. I think this is a major limitation and a source of errors.

```python
from typing import Union
import typic


# Case A. Incorrect. Expected: ValueError
print(typic.coerce("foo", Union[float, int]))  # foo

from enum import Enum

class MyEnum(Enum):
  a = "foo"
  b = "bar"

# Case C1. Correct: Union with None works.
print(typic.coerce("foo", Union[MyEnum, None]))  # MyEnum.a
print(typic.coerce(None, Union[MyEnum, None]))  # None

# Case C1. Incorrect. Expected: MyEnum.a
print(typic.coerce("foo", Union[MyEnum, int]))  # foo
print(typic.coerce("foo", Union[MyEnum, bool]))  # foo

class Sentinel:
  pass

# Case B. Incorrect. Expected: MyEnum.a
print(typic.coerce("foo", Union[MyEnum, Sentinel]))  # foo

# Case C1: Correct: The value is an instance of one of the types
print(typic.coerce(1, Union[bool, int]))  # 1
print(typic.coerce(False, Union[bool, int]))  # False

# Case B. Incorrect. Expected: True (since it can be coerced to bool, but not to int)
print(typic.coerce("asdf", Union[bool, int]))  # asdf

# Case C2. Expected: TypeError, since it could be coerced to both
print(typic.coerce("1", Union[bool, int]))  # 1


```

Would it really be problematic to handle coercing to Union in some cases?

I can imagine scenarios where it's unambiguous, and one scenario where it is and an error could be raised:
- A. If the value cannot be coerced to any of the types: raise one of the coercion errors (e.g. the last)
- B. If the value can be coerced to only one of the types (the others may raise ValueError/TypeError): return that coerced value
- C. If the value can be coerced to multiple of the types:
  - C1: If the value is an instance of one of the union's types, then "coerce" it to that type -- coerce in this context means just perform any constraint checks that there might be (This coercion is already handled for `Union[T, None]`)
  - C2: Otherwise: Raise a TypeError (this is the ambiguous scenario)

What do you think?

In my mind, it might look something like this:

```python
from typing import Any, Iterable, Type
from typic import coerce

# Sentinel value
class Empty:
    pass


_empty = Empty()


def coerce_union(value: Any, union: Iterable[Type]) -> Any:
    coerced_value = _empty

    for typ in union:
        # If the value is already an instance of one of the types in the Union, coerce using that type
        # Presumably, if the type was constrained, coercing could raise errors here, but that would be expected.
        if isinstance(value, typ):
            return coerce(value, typ)
    error = None

    for typ in union:
        try:
            new_coerced_value = coerce(value, typ)
        except (ValueError, TypeError) as e:
            # Store the error and continue
            error = e
            continue
        if coerced_value is not _empty:
            raise TypeError("Ambiguous coercion: the value could be coerced to multiple types in the Union")
        coerced_value = new_coerced_value
    if coerced_value is not _empty:
        return coerced_value
    # The value couldn't be coerced to any of the types in the Union
    raise error
```

**Comment by seandstewart** [comment]
Thank you for the well-thought-out discussion on Unions. It's a bit of a weird case, since as I note in the documentation, the resolution path for a Union-type is unclear when it comes to coercion, since we don't actually know what the user wants. You do bring up a good point about the runtime validation of Union-types. 

We don't currently do any actual runtime validation beyond the attempt to coerce a type and I feel that this logic bleeds into validation logic rather than coercion logic, but I'll have to think about this a bit more.

**Comment by syastrov** [comment]
You're welcome. I certainly understand the concern about not wanting to guess what the user wants and about adding validation logic.
I already see there is a potential issue in my proposal: In case C1, where you check if the type `isinstance` of one of the types in the Union, you could get multiple matches, due to subclassing: therefore that should also raise an error in the case of multiple valid coercions.

Still, I think ignoring coercion of Unions is not a good idea, because, as far as I understand the idea behind coercion, is that you are guaranteed that you get the target type back or an error is thrown. That's not the case right now for `typic.coerce("foo", Union[float, int])`. I'd prefer some error (e.g. TypeError) to be thrown there.

I wonder if we could make everyone happy by allowing to register a custom Union coercer, with the default being that an error is thrown? (unless it's this special case of `Optional`?)
Currently, it's possible to register a custom coercer for Union using `typic.register` (`typic.register(union_coercer, lambda typ: getattr(typ, "__origin__", typ) == Union)`), but it's not very useful... the coercer function does not get passed the type it's coercing to, so there would be no way to decide which type to coerce to. Therefore, I wouldn't be able to implement the kind of coercion that I outlined. Maybe you'd be willing to add an extra parameter to coerce, passing the target type? Or maybe it should be a separate `register_union_coercer` function or somesuch...

So, if you don't feel inclined to make the library opinionated about this, maybe opening it up for the user to decide is a good choice.

**Comment by syastrov** [comment]
By the way, my original use case was that I have a sentinel value that I default for all values in a class to indicate missing values, e.g.:

```python

class Missing:
    pass


MISSING = Missing()
@typic.al
@dataclass
class PartialBlogEntity:
    title: Union[Optional[str], Missing] = MISSING
```

In that case, I never want typical to coerce to the `Missing` type.

**Comment by seandstewart** [comment]
Here’s a complete example of registering a custom coercer from my library [iambic](https://github.com/seandstewart/iambic/blob/bf5313c8dbd43f87c2cc890eb96a228432bb5faf/iambic/ast/node.py#L496) which makes use of Unions.

In your case, I would probably write a check which looks for a Union as the origin and your `Missing` sentinel as an arg.

**Comment by syastrov** [comment]
Thanks for the example. I can see how it works in this case where you essentially have a discriminated union (e.g. you can check the `"type"` field of the `value` to know what to coerce to) with a fixed set of possible types. But I don't see how I could make this in a generic way, without registering a coercer for each possible Union combination.

For example, if I have more fields, like this:

```python
@typic.al
@dataclass
class PartialBlogEntity:
    title: Union[Optional[str], Missing] = MISSING
    created_at: Union[datetime, Missing] = MISSING
```

I would have to register a coercer with a check function that looked for `Union[Optional[str], Missing]`, which always coerced to `Optional[str]`; then, register another coercer with a check function that looked for `Union[datetime, Missing]` and always coerced to `datetime`.
Am I missing something?

**Comment by seandstewart** [comment]
You could call `typic.coerce` on the nested type within your own coercer.

**Comment by seandstewart** [comment]
@syastrov I believe I've provided a path for something like what you're asking for here in v2.0.0b8. That version should be released today.

**Comment by seandstewart** [comment]
I've been noodling on this a bit and decided it's a good thing to add to the library. We added support for ["tagged unions"](https://python-typical.org/usage/types/#tagged-unions-polymorphic-types) a while back, which solves the main use-case of custom type registration, but there are real cases where it may be useful to allow for this.
