### ISSUE TITLE
Switch to own implementation from dataclasses

### ISSUE THREAD

**Issue by prostomarkeloff** [seandstewart/typical#20]
Heyo! I very like your library! But when i saw the docs, i found that `typical` uses python `dataclasses` from standart library which, of course, will decrease performance because they are slow. What do you think about reinventing it for more performance? :)

**Comment by seandstewart** [comment]
Part of the philosophy for this library is to avoid re-inventing the tools provided by the standard library. One of the reasons I like using dataclasses is that they're standard Python and recognizable. I haven't observed that they are noticeably slower than regular old classes either:

```python
>>> import dataclasses
>>> @dataclasses.dataclass
... class Foo:
...     bar: str
...     
>>> class Bar:
>>>     def __init__(self, foo: str):
...         self.foo = foo
...         
>>> import timeit
>>> timeit.timeit("Foo('bar')", globals=globals())
0.32830730899999594
>>> timeit.timeit("Bar('foo')", globals=globals())
0.30331649500000424
```
Do you have benchmarks which show otherwise?

**Comment by seandstewart** [comment]
I would add that I'm not immediately opposed to the idea, however it's a decent amount of work to undertake and I'm not sure the implementation would be any better than the one that exists in the standard lib, or in the [attrs](https://github.com/python-attrs/attrs) library.

**Comment by syastrov** [comment]
I am also using dataclasses and like them, so don't see the need for another implementation.
Also, performance can be increased using `__slots__` (though that requires hacks when using default values -- see [StackOverflow](https://stackoverflow.com/questions/50180735/how-can-dataclasses-be-made-to-work-better-with-slots)).

```python
>>> import timeit
>>> timeit.timeit("Foo('bar')", globals=globals())
0.2975219330000982
>>> timeit.timeit("Bar('foo')", globals=globals())
0.27735200899996926
>>> class Foo2:
... 
KeyboardInterrupt
>>> @dataclasses.dataclass
... class Foo2:
...   __slots__ = ("bar",)
...   bar: str
... 
>>> timeit.timeit("Foo2('bar')", globals=globals())
0.2451581289999467
>>> timeit.timeit("Foo2('bar')", globals=globals())
0.24343900000008034
```

**Comment by prostomarkeloff** [comment]
Ok, i think your explanation so well for closing question. If using stdlib a part of philosophy `typical` then i really happy of it :)
