### ISSUE TITLE
When using my with typic.mypy plugin get error cannot import name 'TypingType' from 'mypy.typeops'

### ISSUE THREAD

**Issue by ErnestoLoma** [seandstewart/typical#208]
* typical version: 2.8.1
* Python version: 3.9.12
* Operating System: macOS 13.4.1

### Description

When using mypy with typic.mypy configured in mypy.ini I get the following error:
mypy.ini:2: error: Error importing plugin "typic.mypy": cannot import name 'TypingType' from 'mypy.typeops' (/Users/ernesthill/PycharmProjects/Typical/venv/lib/python3.9/site-packages/mypy/typeops.cpython-39-darwin.so)  [misc]
Found 1 error in 1 file (errors prevented further checking)

### What I Did
ran mypy for my project. The version of mypy is 1.5.1

Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
mypy pyatlan
mypy.ini:2: error: Error importing plugin "typic.mypy": cannot import name 'TypingType' from 'mypy.typeops' (/Users/ernesthill/PycharmProjects/Typical/venv/lib/python3.9/site-packages/mypy/typeops.cpython-39-darwin.so)  [misc]
Found 1 error in 1 file (errors prevented further checking)

**Comment by kyle-kc** [comment]
Same problem here. I can't find the `TypingType` class in `mypy.typeops` so I'm guessing it was removed from mypy at some point.

**Comment by seandstewart** [comment]
Yes, the plugin does not work with newer versions of mypy - however if you don't use the @typic.klass decorator, there is largely no need for the plugin.
