### ISSUE TITLE
Comparison to typeguard

### ISSUE THREAD

**Issue by alexmojaki** [seandstewart/typical#24]
I haven't read through this project thoroughly but it looks like it overlaps a lot with https://github.com/agronholm/typeguard, at least on the validation side. Just thought you might want to know about it and maybe mention it in your docs somewhere. Maybe you two can even help each other.

**Comment by seandstewart** [comment]
Thanks for this, @alexmojaki - I’ll be sure to reach out!

**Comment by slippycheeze** [comment]
FWIW, since I'm here for a related reason, I do rather like `typeguard`'s import hook support for decorating all the callables and classes in a module with strict validation.  Probably the one thing I'd like in typical that isn't there.
