### ISSUE TITLE
docs: The example which mentions that pydantic will raise an exception is not accurate 

### ISSUE THREAD

**Issue by pmav99** [seandstewart/typical#25]
According to the [docs](https://github.com/seandstewart/typical/blob/0892f69930d31a60883e7d5a3c2391d3590b497e/docs/usage/strict-mode.rst):

> For instance, pydantic will coerce a float to an int, but will raise an error if a str is passed to a field marked as datetime.

This is not true:
``` python
import datetime
import pydantic

class Foo(pydantic.BaseModel):
    a_date: datetime.date
    a_datetime: datetime.datetime

a = Foo(a_date="2019-01-01", a_datetime="2019-01-01 17:31:31")
print(type(a.a_date))
print(type(a.a_datetime))
```
You might want to rephrase that

**Comment by seandstewart** [comment]
That’s no good, thank you for catching that. I seem to recall having to write custom validators for date-time fields, but that must have changed.

**Comment by pmav99** [comment]
Maybe it was true in older versions, but at least for the past 6 months, which is how long I have been using pydantic, it has been coercing strings to datetime. Of course, if you need a specific format, you will still need to write a custom validator

**Comment by seandstewart** [comment]
@pmav99 thanks again for flagging this, I've merged an update to the docs that removes this inaccuracy. 🌮
