### ISSUE TITLE
Custom validation feature request

### ISSUE THREAD

**Issue by jae-lee** [seandstewart/typical#31]
### Description

Would like to see a feature to implement custom validations that could span multiple fields. For example:

Let's say you had a vacation start date and vacation end date field. Vacation start date should be before vacation end date.

**Comment by kfollesdal** [comment]
@jae-lee maybe I misunderstand. but can you use __post_init__ to validate dependent types? 

import typic
from datetime import datetime


@typic.klass
class DateCheck:
    start: datetime
    end: datetime

    def __post_init__(self):
        if self.start > self.end:
            raise ValueError("Start date have to be before end date.")

**Comment by MVrachev** [comment]
I agree this will be an awesome feature.
Many times you want a deeper validation beyond type checks which you can only implement. 

What is the status of this issue?
