### ISSUE TITLE
Error with class name collisions

### ISSUE THREAD

**Issue by gkaemmer** [seandstewart/typical#66]
* typical version: 2.0.6
* Python version: 3.8.1
* Operating System: Mac OSX

### Description

Ran into some weird bugs when using multiple classes with the same name (defined in different files). There must be some kind of caching-by-class-name going on.

Seems to be related to calling `.transmute()` with one another as an argument.

### What I Did

```python
# index.py
from other import my_function
import typic

@typic.klass
class MyClass:
  field: int
  def __post_init__(self):
    print("index.py: MyClass is being constructed")

# Construct a MyClass in other.py
other = my_function()

# Construct a local MyClass
MyClass(field=1)

# This should only construct a local MyClass, but instead calls __post_init__
# in other.py
MyClass.transmute(other)



# other.py
import typic

@typic.klass
class MyClass:
  field: int
  def __post_init__(self):
    print("other.py: MyClass is being constructed")

def my_function():
  val = MyClass(field=1)
  return val
```

Running `python index.py` prints this:
```
other.py: MyClass is being constructed
index.py: MyClass is being constructed
other.py: MyClass is being constructed
```
You would expect this:
```
other.py: MyClass is being constructed
index.py: MyClass is being constructed
index.py: MyClass is being constructed
```

**Comment by seandstewart** [comment]
Thanks for the clear test case @gkaemmer -

We're not explicitly caching by name, but there's definitely something nefarious going on here...
