### ISSUE TITLE
Consider using lazy stringification for field paths where possible

### ISSUE THREAD

**Issue by slippycheeze** [seandstewart/typical#81]
* typical version: 2.0.12 / master

Right now typical eagerly generates the field path for displaying in error messages.  This should ideally be lazy, so that the cost of a potentially complex `__str__` or `__repr__` is avoided in the common -- non-failure -- case.

This costs an object construction and a couple refcounts, but avoids creating and destroying just as many strings as those objects -- and storing a list is probably cheap enough.

I'm sure there is a module for this, but last time I needed it I just wrote my own.  The implementation is pretty trivial, honestly, but this is off the top of my head, and in the github editor, so if it don't compile, don't be surprised. :)

```
class LazyReprConcat(object):
  __slots__ = ['things']
  def __init__(self, *things):
    self.things = things
  def __str__(self):
    return ''.join(repr(thing) for thing in self.things)
  __repr__ = __str__
```

The reason it did the concat was to allow easy recursive use: `field = LazyReprConcat(parentPath, fieldName)`, but there are probably a million viable ways to handle all that, including more automagic with `+` and stuff...

**Comment by seandstewart** [comment]
Great idea - I may work this into the patch for #80
