### ISSUE TITLE
Validation of Literal types

### ISSUE THREAD

**Issue by vinceatbluelabs** [seandstewart/typical#87]
[Literal](https://mypy.readthedocs.io/en/stable/literal_types.html) is a way of specifying that a variable is one of a set of specific values.

It'd be great if typical would be able to validate data using Literal annotations.

An example where I did a similar validation manually: https://github.com/bluelabsio/records-mover/blob/master/records_mover/records/delimited/hint.py#L43-L71

**Comment by seandstewart** [comment]
Hey @vinceatbluelabs - 

Thanks for your submission! I'll have a look at this in the coming days.

**Comment by seandstewart** [comment]
Hey @vinceatbluelabs  - 

I've just merged experimental support for this feature to the `v2.1` branch. If you're willing, I'd appreciate feedback on the interface!
