### ISSUE TITLE
typic.validate bug?

### ISSUE THREAD

**Issue by kfollesdal** [seandstewart/typical#88]
* typical version: 2.0.15
* Python version: 3.8.2
* Operating System: macOS

Did not expected this. Have I misunderstood something?
```
typic.validate(int, 'a')
#> 'a'
```

**Comment by seandstewart** [comment]
Looks like this is a hold-over from pre-2.0. The Deserializer factory optimizes itself by caching results for builtins on init, but that resulted in an invalid validator, since no constraints were provided.

I've already got a fix simple fix that should get released tonight.
