### ISSUE TITLE
transmute from datetime.datetime -> pendulum.Datetime not handling tzinfo right

### ISSUE THREAD

**Issue by kfollesdal** [seandstewart/typical#91]
* typical version: 2.0.16
* Python version: 3.8.2
* Operating System: macOS

Hi again, 
I should probably soon try to make some pr, but take some time to understand the structure of typical and how things is put together. But until then here are an observation of a something that do not behave as expected.

```
import typic
import pendulum
from datetime import datetime
import pytz

dt = datetime(2020,5,24,tzinfo=pytz.UTC)
```

I would expect that,
```
x = typic.transmute(pendulum.DateTime, dt)
x
#> DateTime(2020, 5, 24, 0, 0, 0, tzinfo=UTC)
```

give same the same as,
```
y = pendulum.instance(dt)
y
#> DateTime(2020, 5, 24, 0, 0, 0, tzinfo=Timezone('UTC'))
```
but as you can see timezone type is diffrent
```
type(x.tzinfo)
#> pytz.UTC
type(y.tzinfo)
#> pendulum.tz.timezone.FixedTimezone
```

What do you think?

**Comment by seandstewart** [comment]
Interesting - I was actually unaware of this factory method. Should be easy enough to add in support.
