### ISSUE TITLE
add methods, eg dict, tuple, namedtuple, and attr __typic_fields_tuple__ to the class decorated by typic.klass

### ISSUE THREAD

**Issue by xbanke** [seandstewart/typical#93]
* typical version: 2.0.17
* Python version: 3.7.4
* Operating System: Centos8

### Description

There's many cases that user wants to transform the data object to a common dict, tuple, or namedtuple. Method `dict` maybe have some args like `exclude` or `include_private` and so on.

The attr named `__typic_fields_tuple__`, maybe some other name, is a tuple only contains the filed names. Although `__typic_fileds__` is also a tuple, but contains detailed field info. Everytime I want to get the field names, I have to do something like:

```py
fields = [f.name for f in self.__typic_fields__]
```

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by seandstewart** [comment]
Hey @xbanke -

Check out the `__serde_flags__` attribute and the `__serde_protocols__` attribute - these should provide the introspection you're looking for.

`__typic_fields__` is meant to provide a dataclass-style `fields` attribute, but isn't quite as nice for more dynamic introspection.

**Comment by seandstewart** [comment]
@xbanke - I should have directed you to the high-level functions `typic.protocol(<obj>)` and `typic.protocols(<obj or callable>)` - these are more stable as they don't make use of internal APIs.
