### ISSUE TITLE
bugs for IntEnum

### ISSUE THREAD

**Issue by xbanke** [seandstewart/typical#98]
* typical version: 2.0.15
* Python version: 3.7.4
* Operating System:

### Description

If a model with IntEnum field and has a default value, the value will not be transmuted when assign this field with the default int value:

```py
import enum
import typic


class T(enum.IntEnum):
    a = 1
    b = -1


@typic.klass
class Foo:
    t: T = T.a

foo = Foo()
foo  # Foo(t=<T.a: 1>)
foo.a = 1
foo  # Foo(t=1)
foo = Foo(1)
foo  # Foo(t=1)
```

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by seandstewart** [comment]
This is a tricky one -- enums which subclass builtins pass equality and instance checks for both enums and the builtin type.
